### Criando um medicamento

POST http://localhost:3000/medications HTTP/1.1
Content-Type: application/json 

{
     "name": "Paracetamol",
     "quantity": 500,
     "type": "comprimidos",
     "expiresAt": "2025-09-04T19:51:38.868Z"
}

### Ler um medicamento

GET http://localhost:3000/medications HTTP/1.1
Content-Type: application/json

//GET não envia nada para o banco de dados, portanto não possui body
// a ? depois do get é uma query, que precisa de uma chave e um valor que deseja ser buscado. ex: users?name=rafael&cpf=12345678910

### Filtrar um medicamento por nome

GET http://localhost:3000/medications?name=Paracetamol HTTP/1.1
Content-Type: application/json

### Filtrar um medicamento por tipo

GET http://localhost:3000/medications?type=comprimidos HTTP/1.1
Content-Type: application/json

### Ler um medicamento pelo id (depois da ultima barra temos um "params" ( chamado no controller por req.params))

GET http://localhost:3000/users/1 HTTP/1.1
Content-Type: application/json

### Delete um medicamento pelo id

DELETE http://localhost:3000/users/2 HTTP/1.1
Content-Type: application/json