@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjUsImNwZiI6IjEyMzQ1Njc4OTExIiwibmFtZSI6IkVkdWFyZG8iLCJyb2xlIjoiRE9DVE9SIiwiaWF0IjoxNzU5ODU2MjA2LCJleHAiOjE3NTk4ODUwMDZ9.GnQEvJyynAzP9MSc3YcE4l4nRylYb_pXUTubTmZ8fks

### aqui criar um record
POST http://localhost:3000/records HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "patientId":3,
    "appointmentDate":"2025-09-15",
    "anotacao":"q"
}

### aqui busca todos
GET http://localhost:3000/records HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

### Ler records(histórico) de um paciente específico(no caso com id 1)

get http://localhost:3000/records?patientId=1 HTTP/1.1
Content-Type: application/json

### ler appointments de um paciente específico(no caso com id 1)
get http://localhost:3000/records?appointments="2025-09-05"HTTP/1.1
Content-Type: application/json


### ler usuario pelso id------------ um intem
get http://localhost:3000/records/1  HTTP/1.1
Content-Type: application/json

### deletar um record pelo id
DELETE http://localhost:3000/records/2 HTTP/1.1
Content-Type: application/json

### fazer upadate de um record
PUT http://localhost:3000/records/1 HTTP/1.1
Content-Type: application/json

{
    "appointmentDate": "9999-09-05T00:00:00.000Z"
}
