POST http://localhost:3000/users HTTP/1.1
Content-Type: application/json

{
    "patientId": 1,
    "appointmentDate":"2025-09-17T19:51:38.868Z"
}

GET http://localhost:3000/users HTTP/1.1
Content-Type: application/json
