@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsImNwZiI6IjEyMzQ2Nzg5MDIiLCJuYW1lIjoiRE9DVE9SIiwiZ3JvdXAiOlsiRE9DVE9SIl0sImlhdCI6MTc2MTA2NjQ3MSwiZXhwIjoxNzcxNDM0NDcxfQ.QU3xFkeM6-rLO2Ml02O2aPnxux6oOrDP07evzYnNEBE
### aqui criar um record

POST https://projeto-integrador-lf6v.onrender.com/records HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "patientId":41,
    "appointmentDate":"2025-09-15",
    "level":5,
    "symptom":"dor na cabeça", 
    "recentMedicine":"Dipirona" 
}

### aqui busca todos

GET https://projeto-integrador-lf6v.onrender.com/records HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

### Ler records(histórico) de um paciente específico(no caso com id 1)

get http://localhost:3000/records?patientId=1 HTTP/1.1
Content-Type: application/json

### ler appointments de um paciente específico(no caso com id 1)
get http://localhost:3000/records?appointments="2025-09-05"HTTP/1.1
Content-Type: application/json


### ler usuario pelso id------------ um intem
get http://localhost:3000/records/1  HTTP/1.1
Content-Type: application/json

### deletar um record pelo id
DELETE http://localhost:3000/records/2 HTTP/1.1
Content-Type: application/json

### fazer upadate de um record
PUT http://localhost:3000/records/1 HTTP/1.1
Content-Type: application/json

{
    "appointmentDate": "9999-09-05T00:00:00.000Z"
}
