### Criando um usuário

POST http://localhost:3000/users HTTP/1.1
Content-Type: application/json

{
    "name":"Eduardo",
    "lastName":"Coppi",
    "password":"123456",
    "cpf":"12345678910",
    "phone":"16994030052",
    "email":"educoppi8@gmail.com",
    "role":"RECEPCIONIST"
}

### Ler todos os Usuários

GET http://localhost:3000/users HTTP/1.1
Content-Type: application/json

### Ler todos os Usuários que começam o nome eduardo

GET http://localhost:3000/users?name=Eduardo HTTP/1.1
Content-Type: application/json

### Ler todos os Usuários que começam o cpf

GET http://localhost:3000/users?cpf=12345678910 HTTP/1.1
Content-Type: application/json
