POST http://localhost:3000/users HTTP/1.1
content-type: application/json

{
    "name":"Eduardo",
    "lastName":"Coppi",
    "password":"123456",
    "cpf":"12345678910",
    "phone":"16994030052",
    "email":"educoppi8@gmail.com",
    "role":"RECEPCIONIST"
}
